version: '3.4'

services:
  configee-web:
    image: configee-web
    build:
      context: src/web/.
      network: host
      dockerfile: Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    ports:
      - "10200:80"
 
networks:
  main-network:
    driver: bridge