version: '3.4'

services:
  configee-nginx:
    build:
      context: src/nginx/.
      network: host
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:80'
    depends_on:
      - configee-web
      - configee-api
    restart: unless-stopped
    networks:
      - main-network

  configee-web:
    image: configee-web
    build:
      context: src/web/.
      network: host
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 1
    depends_on:
     - configee-api
    networks:
      - main-network

  configee-api:
   image: configee-api
   build:
     context: src/backend/.
     dockerfile: Configee.API/Dockerfile
   restart: unless-stopped
   networks:
     - main-network

 
networks:
  main-network:
    driver: bridge